import { STORE_ADMIN } from "./adminActions";
import {
  ALLEMPLOYEE_FAIL,
  ALLEMPLOYEE_SUCCESS,
  ADD_EMPLOYEE_LOADING,
  ADD_EMPLOYEE_SUCCESS,
  ADD_EMPLOYEE_FAIL,
  CLOSE_MODAL,
  ACCT_NO,
  ACCT_NO_ERR,
  GET_BANK,
} from "./employeeActions";

export {
  STORE_ADMIN,
  ALLEMPLOYEE_SUCCESS,
  ALLEMPLOYEE_FAIL,
  ADD_EMPLOYEE_FAIL,
  ADD_EMPLOYEE_SUCCESS,
  CLOSE_MODAL,
  ADD_EMPLOYEE_LOADING,
  ACCT_NO,
  ACCT_NO_ERR,
  GET_BANK,
};
